In [1]:
import tensorflow as tf

# 两行三列零矩阵
mat0 = tf.constant([[0,0,0],[0,0,0]])

# 两行三列零矩阵
mat1 = tf.zeros([2,3])

# 三行两列一矩阵
mat2 = tf.ones([3,2])

# 两行三列填充矩阵(15)
mat3 = tf.fill([2,3],15)
with tf.Session() as sess:
    print(sess.run(mat0))
    print('************')
    print(sess.run(mat1))
    print('************')
    print(sess.run(mat2))
    print('************')
    print(sess.run(mat3))

[[0 0 0]
 [0 0 0]]
************
[[0. 0. 0.]
 [0. 0. 0.]]
************
[[1. 1.]
 [1. 1.]
 [1. 1.]]
************
[[15 15 15]
 [15 15 15]]


### 一些更为特殊的矩阵

In [2]:
import tensorflow as tf
# 三行一列的矩阵
mat1 = tf.constant([[2],[3],[4]])
# 与mat1具有相同的维度，但mat2内容为0
mat2 = tf.zeros_like(mat1)

# 将0-2之间数据分成相等的10份，中间有10个数据，要填11
mat3 = tf.linspace(0.0,2.0,11)

# 随机数矩阵，2行三列，数字为-1到2之间的随机数
mat4 = tf.random_uniform([2,3],-1,2)


with tf.Session() as sess:
    print(sess.run(mat2))
    print('************')
    print(sess.run(mat3))
    print('************')
    print(sess.run(mat4))

[[0]
 [0]
 [0]]
************
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
************
[[ 0.5634475  -0.28132176  1.3105965 ]
 [ 1.5659862   0.65178156 -0.8895434 ]]
