### 类比数据的学习: CURD

In [1]:
# CURD
import numpy as np

# 一维数组
data1 = np.array([1,2,3,4,5])
print(data1)
print('***************')

# 两行两列数组
data2 = np.array([[1,2],
                  [3,4]])
print(data2)
print('***************')

# 矩阵的维度
print(data1.shape,data2.shape)
print('***************')

# 初始化特殊矩阵 zeros ones
print(np.zeros([2,3]),np.ones([2,2]))
print('***************')

# 改查: 修改第二行第一列数据
data2[1,0] = 5
print(data2)
# 查询第二行第二列数据
print(data2[1,1])
print('***************')

# 基本运算:加减乘除

# 两行三列的全一矩阵
data3 = np.ones([2,3])

# 简单乘除加法
print(data3*2) # 对应每个元素乘2
print(data3/3) # 对应元素除以3
print(data3+2) # 所有元素加2
print('***************')

# 矩阵 +*

# 两行三列矩阵
data4 = np.array([[1,2,3],[4,5,6]])

# 矩阵对应位置元素相加
print(data3+data4)
print('***************')

# 矩阵对应位置元素相乘
print(data3*data4)

[1 2 3 4 5]
***************
[[1 2]
 [3 4]]
***************
(5,) (2, 2)
***************
[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]]
***************
[[1 2]
 [5 4]]
4
***************
[[2. 2. 2.]
 [2. 2. 2.]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
[[3. 3. 3.]
 [3. 3. 3.]]
***************
[[2. 3. 4.]
 [5. 6. 7.]]
***************
[[1. 2. 3.]
 [4. 5. 6.]]
